// Canonical Ostadix hosted-backend catalog.
//
// This file deliberately contains only macro invocations and literal tokens.
// The authoritative runtime expands it into `BackendSpec` values, while
// dependency-isolated tooling (notably the MCP server) can expand the same
// records into its own purpose-specific view without linking the O runtime or
// parsing a manifest at startup.
//
// Runtime alternatives are ordered disjunctions of ordered conjunctions:
// `[["dotnet"], ["mcs", "mono"]]` means dotnet OR (mcs AND mono).

backend_catalog_metadata! {
    current_schema: "ostadix.backend-catalog/v5",
    legacy_schema_v4: "ostadix.backend-catalog/v4",
    legacy_schema_v3: "ostadix.backend-catalog/v3",
}

runtime_requirement_catalog! {
    {
        key: "builtin",
        builtin: true,
        precision: Exact,
        alternatives: [],
    },
    {
        key: "python",
        builtin: false,
        precision: Exact,
        alternatives: [["python3"]],
    },
    {
        key: "bash",
        builtin: false,
        precision: Exact,
        alternatives: [["bash"]],
    },
    {
        key: "shell",
        builtin: false,
        precision: Exact,
        alternatives: [["sh"]],
    },
    {
        key: "javascript",
        builtin: false,
        precision: Exact,
        alternatives: [["node"]],
    },
    {
        key: "ruby",
        builtin: false,
        precision: Exact,
        alternatives: [["ruby"]],
    },
    {
        key: "rust",
        builtin: false,
        precision: Exact,
        alternatives: [["rustc"]],
    },
    {
        key: "c",
        builtin: false,
        precision: Exact,
        alternatives: [["cc"]],
    },
    {
        key: "cpp",
        builtin: false,
        precision: Exact,
        alternatives: [["g++"]],
    },
    {
        key: "java",
        builtin: false,
        precision: Exact,
        alternatives: [["javac", "java"]],
    },
    {
        key: "nix",
        builtin: false,
        precision: Exact,
        alternatives: [["nix"]],
    },
    {
        key: "nixos_test",
        builtin: false,
        // The non-Linux compatibility path is a bounded stub and does not
        // invoke Nix. This backend-wide requirement is therefore a safe
        // over-approximation rather than an exact per-host requirement.
        precision: ConservativeAllSources,
        alternatives: [["python3", "nix"]],
    },
    {
        key: "sql",
        builtin: false,
        precision: Exact,
        alternatives: [["sqlite3"]],
    },
    {
        key: "haskell",
        builtin: false,
        precision: Exact,
        alternatives: [["runghc"], ["ghc"]],
    },
    {
        key: "ocaml",
        builtin: false,
        precision: Exact,
        alternatives: [["ocaml"], ["ocamlopt"], ["ocamlc"]],
    },
    {
        key: "racket",
        builtin: false,
        precision: Exact,
        alternatives: [["racket"]],
    },
    {
        key: "common_lisp",
        builtin: false,
        precision: Exact,
        alternatives: [["sbcl"], ["clisp"]],
    },
    {
        key: "csharp",
        builtin: false,
        precision: Exact,
        alternatives: [["dotnet"], ["mcs", "mono"]],
    },
    {
        key: "matlab",
        builtin: false,
        precision: Exact,
        alternatives: [["octave"], ["matlab"]],
    },
    {
        key: "mathematica",
        builtin: false,
        precision: Exact,
        alternatives: [["wolframscript"]],
    },
    {
        key: "webassembly",
        builtin: false,
        // A text converter is needed only for WAT-shaped bodies. The catalog's
        // backend-wide view intentionally over-approximates that condition;
        // operation-specific runtime evidence may refine it later. Keep the
        // original WABT alternatives first so their published indices remain
        // stable, then admit the wasm-tools converter shipped by Alpine.
        precision: ConservativeAllSources,
        alternatives: [
            ["wat2wasm", "wasmtime"],
            ["wat2wasm", "wasmer"],
            ["wasm-tools", "wasmtime"],
            ["wasm-tools", "wasmer"],
        ],
    },
    {
        key: "ubuntu_vm",
        builtin: false,
        precision: Exact,
        alternatives: [["python3", "multipass"]],
    },
}

backend_catalog! {
    {
        name: "O",
        aliases: ["o"],
        pure: false,
        renderer: Default,
        execution: InlineAst,
        authorities: [],
        adapter: Inline,
        runtime: "builtin",
        integer_exactness: Arbitrary,
        rich_numbers: Preserved,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "quote",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: InlineAst,
        authorities: [],
        adapter: Inline,
        runtime: "builtin",
        integer_exactness: Unknown,
        rich_numbers: Unknown,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "nix",
        aliases: [],
        pure: false,
        renderer: Nix,
        execution: Shim,
        authorities: [FileRead, FileWrite, Network, Process],
        adapter: NativeRust,
        runtime: "nix",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "nix_expr",
        aliases: [],
        pure: true,
        renderer: Default,
        execution: InlineValue,
        authorities: [],
        // Normal OIR evaluation is inline, but the backend wire endpoint also
        // retains the native Rust `run_nix` implementation for direct calls.
        adapter: NativeRust,
        runtime: "builtin",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "nix_store",
        aliases: [],
        pure: false,
        renderer: Nix,
        execution: Shim,
        authorities: [FileRead, FileWrite, Network, Process],
        adapter: NativeRust,
        runtime: "nix",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "nixos_test",
        aliases: [],
        pure: false,
        renderer: Nix,
        execution: Shim,
        authorities: [FileRead, FileWrite, Network, Process],
        adapter: LegacyPythonShim,
        runtime: "nixos_test",
        integer_exactness: Unknown,
        rich_numbers: Unknown,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "html",
        aliases: [],
        pure: true,
        renderer: Html,
        execution: InlineValue,
        authorities: [],
        adapter: Inline,
        runtime: "builtin",
        integer_exactness: Arbitrary,
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "markdown",
        aliases: ["md"],
        pure: true,
        renderer: Markdown,
        execution: InlineValue,
        authorities: [],
        adapter: Inline,
        runtime: "builtin",
        integer_exactness: Arbitrary,
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "latex",
        aliases: ["tex"],
        pure: true,
        renderer: Latex,
        execution: InlineValue,
        authorities: [],
        adapter: Inline,
        runtime: "builtin",
        integer_exactness: Arbitrary,
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "text",
        aliases: ["plain"],
        pure: true,
        renderer: Default,
        execution: InlineValue,
        authorities: [],
        adapter: Inline,
        runtime: "builtin",
        integer_exactness: Arbitrary,
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "sql",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [],
        adapter: NativeRust,
        runtime: "sql",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: SemanticSnapshot {
            codec: "ostadix.sqlite-cli-main/v1",
            compatibility: ExactImplementation,
        },
        morphism_profile: None,
    },
    {
        name: "haskell",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "haskell",
        integer_exactness: Arbitrary,
        rich_numbers: Preserved,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "ocaml",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "ocaml",
        integer_exactness: Unknown,
        rich_numbers: Unknown,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "webassembly",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "webassembly",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "python",
        aliases: ["py"],
        pure: false,
        renderer: Python,
        execution: Shim,
        authorities: [],
        adapter: LegacyPythonShim,
        runtime: "python",
        integer_exactness: Arbitrary,
        rich_numbers: Preserved,
        state_support: SemanticSnapshot {
            codec: "ostadix.python-graph/v1",
            compatibility: ExactImplementation,
        },
        morphism_profile: PythonPlainData,
    },
    {
        name: "ubuntu_vm",
        aliases: ["ubuntu"],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [Process],
        adapter: LegacyPythonShim,
        runtime: "ubuntu_vm",
        integer_exactness: Unknown,
        rich_numbers: Unknown,
        state_support: ExternalPinned {
            manifest_schema: "ostadix.multipass-resource/v1",
        },
        morphism_profile: None,
    },
    {
        name: "bash",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [Process],
        adapter: NativeRust,
        runtime: "bash",
        integer_exactness: Unknown,
        rich_numbers: Unknown,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "shell",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [Process],
        adapter: NativeRust,
        runtime: "shell",
        integer_exactness: Unknown,
        rich_numbers: Unknown,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "rust",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "rust",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: RustSourceConstantStdout,
    },
    {
        name: "racket",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "racket",
        integer_exactness: Arbitrary,
        rich_numbers: Preserved,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "csharp",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "csharp",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "c",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "c",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "cpp",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "cpp",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "lisp",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "common_lisp",
        integer_exactness: Arbitrary,
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "common_lisp",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "common_lisp",
        integer_exactness: Arbitrary,
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "ruby",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "ruby",
        integer_exactness: Arbitrary,
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "matlab",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "matlab",
        integer_exactness: ExactMagnitudeBits(53),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "mathematica",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "mathematica",
        integer_exactness: Arbitrary,
        rich_numbers: Preserved,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "java",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "java",
        integer_exactness: TwosComplementBits(63),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: None,
    },
    {
        name: "javascript",
        aliases: [],
        pure: false,
        renderer: Default,
        execution: Shim,
        authorities: [FileWrite, Process],
        adapter: NativeRust,
        runtime: "javascript",
        integer_exactness: ExactMagnitudeBits(53),
        rich_numbers: Collapsed,
        state_support: Stateless,
        morphism_profile: JavascriptBindingStdout,
    },
}
