//! Core project, route, and result types.
//!
//! Everything here is `serde`-serializable with deterministic ordering
//! (`BTreeMap` for keyed collections, `Vec` for ordered collections). These
//! types are the vocabulary shared by bundling, discovery, manifest parsing,
//! materialization, the route runtime, and the `.O` lowering.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::path::PathBuf;

/// The on-disk/on-wire format version of a [`ProjectBundle`].
pub const BUNDLE_FORMAT_VERSION: u32 = 2;

// ─────────────────────────────────────────────────────────────────────────────
// base64 helper for byte payloads inside JSON
// ─────────────────────────────────────────────────────────────────────────────

/// Serialize `Vec<u8>` as a base64 string so JSON bundles stay text-clean and
/// lossless for arbitrary binary assets.
pub(crate) mod b64_bytes {
    use base64::{engine::general_purpose::STANDARD as B64, Engine};
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(bytes: &[u8], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&B64.encode(bytes))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = String::deserialize(d)?;
        B64.decode(s.as_bytes()).map_err(serde::de::Error::custom)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Files
// ─────────────────────────────────────────────────────────────────────────────

/// The semantic role a stored file plays in the project.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum FileRole {
    /// Human-authored source in some language.
    Source,
    /// Binary or textual asset (data, images, fixtures, …).
    Asset,
    /// A build/config manifest (Cargo.toml, package.json, pyproject.toml, …).
    Manifest,
    /// Route metadata generated by O-lang tooling.
    GeneratedRouteMetadata,
    /// A file identified as a runnable entrypoint.
    Entrypoint,
    /// Anything else (empty files, extensionless files, unclassified).
    #[default]
    Other,
}

/// A single file captured losslessly inside a [`ProjectBundle`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProjectFile {
    /// Normalized, relative, `/`-separated path. Never absolute, never `..`.
    pub path: String,
    /// Raw file bytes. Serialized as base64 in JSON.
    #[serde(with = "b64_bytes")]
    pub bytes: Vec<u8>,
    /// Whether the executable bit is set (any of the unix exec bits).
    pub executable: bool,
    /// The full unix permission mode, when known.
    pub unix_mode: Option<u32>,
    /// If this entry is a symlink, its (relative, in-root) target.
    pub symlink_target: Option<String>,
    /// The O-lang backend/evaluator name inferred for this file, if any.
    pub evaluator: Option<String>,
    /// Lowercase hex sha256 of `bytes` (or of the link target for symlinks).
    pub content_hash: String,
    /// The semantic role of this file.
    pub role: FileRole,
}

impl ProjectFile {
    /// True when this entry represents a symbolic link rather than a regular
    /// file.
    pub fn is_symlink(&self) -> bool {
        self.symlink_target.is_some()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Routes
// ─────────────────────────────────────────────────────────────────────────────

/// The broad category of a route, used for reporting and lowering.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum RouteKind {
    /// A language interpreter invoked with a script (e.g. `python3 main.py`).
    InterpreterCommand,
    /// A prebuilt native binary invoked directly.
    CompiledBinary,
    /// A build step that produces artifacts (e.g. `cargo build`).
    BuildTarget,
    /// A package-declared entrypoint (`[project.scripts]`, `bin`, …).
    PackageEntrypoint,
    /// A shell task / script runner target (npm scripts, Makefile targets).
    #[default]
    ShellTask,
    /// An O-lang evaluator block.
    OEvaluator,
    /// A composite route that sequences prerequisites into one logical run.
    Composite,
}

/// How the stdout of a route should be interpreted into a structured value.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResultCodec {
    /// Treat stdout as opaque UTF-8 text.
    #[default]
    Text,
    /// Parse stdout as JSON into `OExecutionResult.value`.
    Json,
    /// Treat stdout as raw bytes only.
    Bytes,
}

impl ResultCodec {
    /// Parse a manifest/CLI codec token. Unknown tokens fall back to `Text`.
    pub fn parse(token: &str) -> ResultCodec {
        match token.trim().to_ascii_lowercase().as_str() {
            "json" => ResultCodec::Json,
            "bytes" | "binary" | "blob" => ResultCodec::Bytes,
            _ => ResultCodec::Text,
        }
    }
}

/// A precondition that must hold before a route may run.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RouteGuard {
    /// The host OS (`std::env::consts::OS`) must equal this value.
    PlatformOs(String),
    /// The named command must be resolvable on `PATH`.
    CommandAvailable(String),
    /// The named environment variable must be set (non-empty).
    EnvVarSet(String),
}

/// Where a route came from — used for reporting and manifest-wins merging.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RouteProvenance {
    /// Declared explicitly in the project manifest at `path`.
    Manifest { path: String },
    /// Auto-discovered by an ecosystem probe, with human-readable evidence.
    Discovered { ecosystem: String, evidence: String },
    /// Injected/overridden from the command line.
    CliOverride,
}

/// Declared read/write effects of a route. Resource keys are opaque strings
/// like `project:out/**`, `host:/tmp/x`, `env:PATH`, or `network`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct RouteEffects {
    /// The route is known to have no observable side effects.
    pub pure: bool,
    /// The route's effects are unknown / unconstrained (the safe default).
    pub unknown: bool,
    /// Resource keys the route reads.
    pub reads: Vec<String>,
    /// Resource keys the route writes.
    pub writes: Vec<String>,
}

impl RouteEffects {
    /// The conservative default: effects unknown.
    pub fn unknown() -> RouteEffects {
        RouteEffects {
            pure: false,
            unknown: true,
            reads: Vec::new(),
            writes: Vec::new(),
        }
    }
}

/// Evidence supplied by a route contract for continuing with another
/// implementation after this route has executed and settled unsuccessfully.
///
/// This is deliberately narrow. `DeclaredIdempotent` is a bundle-bound author
/// declaration, not proof that the hosted command was sandboxed or that its
/// effects were independently verified. The HGraph coordinator records that
/// exact provenance when it relies on the declaration.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RouteFailureContinuation {
    /// No safe post-execution continuation contract is available.
    #[default]
    Unproven,
    /// Repeating the logical operation after this route settles unsuccessfully
    /// is declared idempotent by the bundle author.
    DeclaredIdempotent,
}

impl RouteFailureContinuation {
    /// Parse the manifest/CLI token without weakening an unknown value to the
    /// fail-closed default silently.
    pub fn parse_checked(token: &str) -> Result<Self, String> {
        match token.trim().to_ascii_lowercase().as_str() {
            "unproven" | "deny" => Ok(Self::Unproven),
            "declared_idempotent" => Ok(Self::DeclaredIdempotent),
            other => Err(format!(
                "unknown failure continuation `{other}`; expected unproven or declared_idempotent"
            )),
        }
    }

    pub const fn token(self) -> &'static str {
        match self {
            Self::Unproven => "unproven",
            Self::DeclaredIdempotent => "declared_idempotent",
        }
    }
}

/// A single, concrete, runnable route through the project.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RouteSpec {
    /// Stable identifier, unique within a bundle.
    pub id: String,
    /// Human-readable label.
    pub label: String,
    /// Broad category.
    pub kind: RouteKind,
    /// The command vector: `command[0]` is the program, the rest are the fixed
    /// leading arguments. `arguments` are appended after these.
    pub command: Vec<String>,
    /// The O-lang evaluator name, when this route runs through one.
    pub evaluator: Option<String>,
    /// The primary entrypoint file (relative path), when applicable.
    pub entrypoint: Option<String>,
    /// Working directory, relative to the project root (`.` for the root).
    pub working_directory: String,
    /// Extra arguments appended to `command`.
    pub arguments: Vec<String>,
    /// Environment overlay applied when running.
    pub environment: BTreeMap<String, String>,
    /// Route ids that must run (in a shared workspace) before this one.
    pub prerequisites: Vec<String>,
    /// Declared input resource keys.
    pub inputs: Vec<String>,
    /// Declared output globs (relative), collected as artifacts after a run.
    pub outputs: Vec<String>,
    /// Declared effects.
    pub effects: RouteEffects,
    /// Bundle-author evidence governing whether ordered selection may continue
    /// after this route actually executes and settles unsuccessfully.
    #[serde(default)]
    pub failure_continuation: RouteFailureContinuation,
    /// How to decode stdout.
    pub result_codec: ResultCodec,
    /// Capability tokens this route provides (used by route sets).
    pub provides: Vec<String>,
    /// Guards evaluated before running.
    pub guards: Vec<RouteGuard>,
    /// Selection priority; higher wins in fallback ordering.
    pub priority: i32,
    /// Whether this route is (a candidate for) the project default.
    pub is_default: bool,
    /// Where this route came from.
    pub provenance: RouteProvenance,
}

impl RouteSpec {
    /// Construct a minimal route with sensible defaults.
    pub fn new(id: impl Into<String>, provenance: RouteProvenance) -> RouteSpec {
        let id = id.into();
        RouteSpec {
            label: id.clone(),
            id,
            kind: RouteKind::default(),
            command: Vec::new(),
            evaluator: None,
            entrypoint: None,
            working_directory: ".".to_string(),
            arguments: Vec::new(),
            environment: BTreeMap::new(),
            prerequisites: Vec::new(),
            inputs: Vec::new(),
            outputs: Vec::new(),
            effects: RouteEffects::unknown(),
            failure_continuation: RouteFailureContinuation::Unproven,
            result_codec: ResultCodec::Text,
            provides: Vec::new(),
            guards: Vec::new(),
            priority: 0,
            is_default: false,
            provenance,
        }
    }

    /// The full argument vector (`command` followed by `arguments`).
    pub fn full_command(&self) -> Vec<String> {
        let mut v = self.command.clone();
        v.extend(self.arguments.iter().cloned());
        v
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Route sets & policies
// ─────────────────────────────────────────────────────────────────────────────

/// The policy that decides which alternative(s) of a [`RouteSet`] execute.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum RoutePolicy {
    /// Run exactly the named route id.
    Explicit(String),
    /// Run the unambiguous default route.
    #[default]
    Default,
    /// Try alternatives in priority/declared order until one succeeds.
    Fallback,
    /// Run alternatives sequentially, returning the first success.
    AnySuccess,
    /// Race alternatives in parallel, return the first success and cancel
    /// the losers cooperatively.
    RaceSuccess,
    /// Race alternatives in parallel, return the first to settle (success or
    /// failure) and cancel the losers cooperatively.
    RaceSettle,
    /// Run every alternative (each in its own isolated workspace).
    All,
    /// Run all in parallel and verify their results are equivalent
    /// (JSON values when decoded, trimmed stdout otherwise).
    VerifyEquivalent,
    /// Run all in parallel and select the fastest successful alternative.
    BenchmarkAndSelect,
}

impl RoutePolicy {
    /// Parse a policy token without silently turning a typo into `default`.
    ///
    /// Manifests retain the compatibility-oriented [`Self::parse`] surface,
    /// while planner/CLI entrypoints use this checked form so the logical
    /// project graph records the policy the caller actually requested.
    pub fn parse_checked(token: &str) -> Result<RoutePolicy, String> {
        let token = token.trim();
        if let Some(rest) = token.strip_prefix("explicit:") {
            let route = rest.trim();
            if route.is_empty() {
                return Err("`explicit:` requires a route id".to_string());
            }
            return Ok(RoutePolicy::Explicit(route.to_string()));
        }
        match token.to_ascii_lowercase().as_str() {
            "explicit" => Ok(RoutePolicy::Explicit(String::new())),
            "default" => Ok(RoutePolicy::Default),
            "fallback" => Ok(RoutePolicy::Fallback),
            "any_success" | "anysuccess" | "any" => Ok(RoutePolicy::AnySuccess),
            "race_success" | "racesuccess" | "race" => Ok(RoutePolicy::RaceSuccess),
            "race_settle" | "racesettle" => Ok(RoutePolicy::RaceSettle),
            "all" => Ok(RoutePolicy::All),
            "verify_equivalent" | "verifyequivalent" | "verify" => {
                Ok(RoutePolicy::VerifyEquivalent)
            }
            "benchmark_and_select" | "benchmarkandselect" | "benchmark" => {
                Ok(RoutePolicy::BenchmarkAndSelect)
            }
            _ => Err(format!(
                "unknown route policy `{token}`; expected explicit[:ROUTE], default, fallback, any_success, race_success, race_settle, all, verify_equivalent, or benchmark_and_select"
            )),
        }
    }

    /// Parse a policy token as used in the manifest / CLI.
    ///
    /// `explicit` requires the route id to be supplied separately (via
    /// `explicit_id`); when absent it degrades to [`RoutePolicy::Default`]
    /// unless the token itself carries it as `explicit:<id>`.
    pub fn parse(token: &str) -> RoutePolicy {
        Self::parse_checked(token).unwrap_or_default()
    }

    /// A short human-readable token for this policy.
    pub fn token(&self) -> String {
        match self {
            RoutePolicy::Explicit(id) if id.is_empty() => "explicit".to_string(),
            RoutePolicy::Explicit(id) => format!("explicit:{id}"),
            RoutePolicy::Default => "default".to_string(),
            RoutePolicy::Fallback => "fallback".to_string(),
            RoutePolicy::AnySuccess => "any_success".to_string(),
            RoutePolicy::RaceSuccess => "race_success".to_string(),
            RoutePolicy::RaceSettle => "race_settle".to_string(),
            RoutePolicy::All => "all".to_string(),
            RoutePolicy::VerifyEquivalent => "verify_equivalent".to_string(),
            RoutePolicy::BenchmarkAndSelect => "benchmark_and_select".to_string(),
        }
    }

    /// Whether the route runtime can currently execute this policy.
    /// Every represented policy is now executable.
    pub fn is_executable(&self) -> bool {
        true
    }
}

/// A named set of alternative routes providing the same capability.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RouteSet {
    /// The capability token these routes provide.
    pub provides: String,
    /// Candidate route ids, in declared order.
    pub alternatives: Vec<String>,
    /// How to select among the alternatives.
    pub policy: RoutePolicy,
}

// ─────────────────────────────────────────────────────────────────────────────
// The bundle
// ─────────────────────────────────────────────────────────────────────────────

/// A lossless, route-preserving snapshot of an entire project.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProjectBundle {
    /// Format version (see [`BUNDLE_FORMAT_VERSION`]).
    pub format_version: u32,
    /// Project name.
    pub name: String,
    /// Deterministic fingerprint of the whole file tree.
    pub root_fingerprint: String,
    /// All captured files, in sorted path order.
    pub files: Vec<ProjectFile>,
    /// All routes, both discovered and manifest-declared.
    pub routes: Vec<RouteSpec>,
    /// Route sets grouping alternative routes by capability.
    pub route_sets: Vec<RouteSet>,
    /// The chosen default route id, if unambiguous.
    pub default_route: Option<String>,
    /// Free-form metadata.
    pub metadata: BTreeMap<String, String>,
}

impl ProjectBundle {
    /// An empty bundle with the given name.
    pub fn empty(name: impl Into<String>) -> ProjectBundle {
        ProjectBundle {
            format_version: BUNDLE_FORMAT_VERSION,
            name: name.into(),
            root_fingerprint: String::new(),
            files: Vec::new(),
            routes: Vec::new(),
            route_sets: Vec::new(),
            default_route: None,
            metadata: BTreeMap::new(),
        }
    }

    /// Look up a route by id.
    pub fn route(&self, id: &str) -> Option<&RouteSpec> {
        self.routes.iter().find(|r| r.id == id)
    }

    /// Look up a route set by its `provides` capability token.
    pub fn route_set(&self, provides: &str) -> Option<&RouteSet> {
        self.route_sets.iter().find(|s| s.provides == provides)
    }

    /// Route ids marked `is_default`.
    pub fn default_candidates(&self) -> Vec<&RouteSpec> {
        self.routes.iter().filter(|r| r.is_default).collect()
    }

    /// Resolve the effective default route id, preferring `default_route`,
    /// then a single `is_default` candidate. Returns `None` when ambiguous or
    /// absent.
    pub fn resolved_default(&self) -> Option<String> {
        if let Some(id) = &self.default_route {
            if self.route(id).is_some() {
                return Some(id.clone());
            }
        }
        let candidates = self.default_candidates();
        if candidates.len() == 1 {
            return Some(candidates[0].id.clone());
        }
        None
    }

    /// Render the route table as human-readable text (no execution).
    pub fn route_table(&self) -> String {
        let mut out = String::new();
        let default = self.resolved_default();
        out.push_str(&format!(
            "Project: {}  ({} route{}, {} route set{})\n",
            self.name,
            self.routes.len(),
            if self.routes.len() == 1 { "" } else { "s" },
            self.route_sets.len(),
            if self.route_sets.len() == 1 { "" } else { "s" },
        ));
        if self.routes.is_empty() {
            out.push_str("  (no routes)\n");
        }
        for route in &self.routes {
            let is_default = default.as_deref() == Some(route.id.as_str());
            let marker = if is_default { "*" } else { " " };
            let provenance = match &route.provenance {
                RouteProvenance::Manifest { path } => format!("manifest:{path}"),
                RouteProvenance::Discovered { ecosystem, .. } => {
                    format!("discovered:{ecosystem}")
                }
                RouteProvenance::CliOverride => "cli".to_string(),
            };
            let command = route.full_command().join(" ");
            out.push_str(&format!(
                "{marker} {id}  [{kind:?}]  provides={provides}  {provenance}\n      $ {command}\n",
                id = route.id,
                kind = route.kind,
                provides = if route.provides.is_empty() {
                    "-".to_string()
                } else {
                    route.provides.join(",")
                },
            ));
        }
        for set in &self.route_sets {
            out.push_str(&format!(
                "  set provides={} policy={} alternatives=[{}]\n",
                set.provides,
                set.policy.token(),
                set.alternatives.join(", "),
            ));
        }
        if default.is_none() && !self.routes.is_empty() {
            out.push_str("  (no unambiguous default route — select one with --route)\n");
        }
        out
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Execution results
// ─────────────────────────────────────────────────────────────────────────────

/// A completely captured output artifact collected after a route runs.
///
/// Missing, unreadable, changing, unsupported, and over-limit declared
/// outputs are rejected before this type is constructed.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Artifact {
    /// Path relative to the execution workspace.
    pub path: String,
    /// Lowercase hex sha256 of the artifact bytes.
    pub content_hash: String,
    /// Length of the artifact in bytes.
    pub bytes_len: u64,
}

/// Why declared artifact evidence is incomplete for a non-successful route.
///
/// This type deliberately contains stable semantic data rather than an opaque
/// I/O string. Successful route results are never allowed to carry one of
/// these states.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum ArtifactCaptureFailure {
    Missing {
        requirement: String,
    },
    Unreadable {
        path: String,
        operation: String,
        error_kind: String,
    },
    ChangedDuringCapture {
        path: String,
        detail: String,
    },
    UnsupportedFileType {
        path: String,
    },
    UnsupportedPathEncoding {
        path_sha256: String,
    },
    OutsideArtifactRoot {
        path: String,
    },
    ArtifactScanLimit {
        limit: usize,
        observed_at_least: usize,
    },
    ArtifactCountLimit {
        limit: usize,
        observed_at_least: usize,
    },
    SingleArtifactLimit {
        path: String,
        limit: u64,
        observed_at_least: u64,
    },
    AggregateArtifactLimit {
        path: String,
        limit: u64,
        captured_before: u64,
        artifact_bytes: u64,
    },
    NotAttempted {
        reason: String,
    },
}

impl ArtifactCaptureFailure {
    pub fn validate(&self) -> Result<(), String> {
        fn text(value: &str, label: &str) -> Result<(), String> {
            if value.is_empty() || value.contains('\0') {
                Err(format!(
                    "artifact capture {label} must be nonempty and contain no NUL"
                ))
            } else {
                Ok(())
            }
        }

        match self {
            Self::Missing { requirement } => text(requirement, "requirement"),
            Self::Unreadable {
                path,
                operation,
                error_kind,
            } => {
                text(path, "path")?;
                text(operation, "operation")?;
                text(error_kind, "error kind")
            }
            Self::ChangedDuringCapture { path, detail } => {
                text(path, "path")?;
                text(detail, "change detail")
            }
            Self::UnsupportedFileType { path } | Self::OutsideArtifactRoot { path } => {
                text(path, "path")
            }
            Self::UnsupportedPathEncoding { path_sha256 } => {
                if path_sha256.len() == 64
                    && path_sha256
                        .bytes()
                        .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
                {
                    Ok(())
                } else {
                    Err("unsupported artifact path SHA-256 is not canonical".to_string())
                }
            }
            Self::ArtifactScanLimit {
                limit,
                observed_at_least,
            } => {
                if observed_at_least <= limit {
                    Err("artifact scan-limit failure does not exceed its limit".to_string())
                } else {
                    Ok(())
                }
            }
            Self::ArtifactCountLimit {
                limit,
                observed_at_least,
            } => {
                if observed_at_least <= limit {
                    Err("artifact count-limit failure does not exceed its limit".to_string())
                } else {
                    Ok(())
                }
            }
            Self::SingleArtifactLimit {
                path,
                limit,
                observed_at_least,
            } => {
                text(path, "path")?;
                if observed_at_least <= limit {
                    Err("single-artifact failure does not exceed its limit".to_string())
                } else {
                    Ok(())
                }
            }
            Self::AggregateArtifactLimit {
                path,
                limit,
                captured_before,
                artifact_bytes,
            } => {
                text(path, "path")?;
                if captured_before
                    .checked_add(*artifact_bytes)
                    .is_some_and(|total| total <= *limit)
                {
                    Err("aggregate-artifact failure does not exceed its limit".to_string())
                } else {
                    Ok(())
                }
            }
            Self::NotAttempted { reason } => text(reason, "not-attempted reason"),
        }
    }
}

/// Whether every declared artifact was captured completely.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "state", rename_all = "snake_case")]
pub enum ArtifactCaptureStatus {
    Complete,
    Incomplete {
        failure: Box<ArtifactCaptureFailure>,
    },
}

impl ArtifactCaptureStatus {
    pub fn is_complete(&self) -> bool {
        matches!(self, Self::Complete)
    }

    pub fn validate(&self) -> Result<(), String> {
        match self {
            Self::Complete => Ok(()),
            Self::Incomplete { failure } => failure.validate(),
        }
    }
}

/// Evidence for one completely drained child-output stream.
///
/// `retained_bytes` describes the bounded prefix stored on
/// [`OExecutionResult`], while `total_observed_bytes` and `sha256` bind the
/// complete stream observed before the route became terminal. A truncated
/// stream is therefore never confused with a complete short stream.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OutputCapture {
    /// Total bytes drained from the child pipe, including discarded suffixes.
    pub total_observed_bytes: u64,
    /// Bytes retained in the corresponding `stdout` or `stderr` vector.
    pub retained_bytes: u64,
    /// Whether bytes were discarded after reaching the retention limit.
    pub truncated: bool,
    /// Lowercase SHA-256 of the complete observed stream.
    pub sha256: String,
}

impl OutputCapture {
    /// Describe a complete, untruncated byte sequence.
    pub fn complete(bytes: &[u8]) -> Self {
        Self {
            total_observed_bytes: bytes.len() as u64,
            retained_bytes: bytes.len() as u64,
            truncated: false,
            sha256: hex::encode(Sha256::digest(bytes)),
        }
    }

    /// Check the metadata that can be verified from the retained prefix.
    pub fn validate_for_retained(&self, retained: &[u8]) -> Result<(), String> {
        let retained_bytes = u64::try_from(retained.len())
            .map_err(|_| "retained output length does not fit u64".to_string())?;
        if self.retained_bytes != retained_bytes {
            return Err(format!(
                "capture retained byte count {} disagrees with retained output length {retained_bytes}",
                self.retained_bytes
            ));
        }
        if self.total_observed_bytes < self.retained_bytes {
            return Err("capture observed fewer bytes than it retained".to_string());
        }
        if self.truncated != (self.total_observed_bytes > self.retained_bytes) {
            return Err(
                "capture truncation flag disagrees with observed and retained lengths".to_string(),
            );
        }
        if self.sha256.len() != 64
            || !self
                .sha256
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err("capture SHA-256 must be 64 lowercase hexadecimal characters".to_string());
        }
        if !self.truncated && self.sha256 != hex::encode(Sha256::digest(retained)) {
            return Err("complete capture SHA-256 disagrees with retained bytes".to_string());
        }
        Ok(())
    }
}

/// Provenance of a single execution — where and how it ran.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExecutionProvenance {
    /// The workspace directory the route ran in.
    pub workspace: PathBuf,
    /// The full command vector that was spawned.
    pub command: Vec<String>,
    /// The working directory the command ran in.
    pub cwd: PathBuf,
}

/// How a valid route result was produced.
///
/// This is deliberately separate from the process exit code: an executed
/// command may settle successfully or unsuccessfully, while a guard skip is a
/// synthetic compatibility result for which no child process was launched.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RouteExecutionDisposition {
    #[default]
    Executed,
    GuardSkipped,
}

/// The result of running one route.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OExecutionResult {
    /// The route id that produced this result.
    pub route_id: String,
    /// Process exit code, if the process ran to completion.
    pub exit_code: Option<i32>,
    /// Captured stdout bytes.
    #[serde(with = "b64_bytes")]
    pub stdout: Vec<u8>,
    /// Complete-stream evidence for the retained stdout prefix.
    pub stdout_capture: OutputCapture,
    /// Captured stderr bytes.
    #[serde(with = "b64_bytes")]
    pub stderr: Vec<u8>,
    /// Complete-stream evidence for the retained stderr prefix.
    pub stderr_capture: OutputCapture,
    /// Decoded structured value (only for `ResultCodec::Json`).
    pub value: Option<serde_json::Value>,
    /// Collected output artifacts.
    pub artifacts: Vec<Artifact>,
    /// Declared output patterns whose capture status this result describes.
    pub artifact_requirements: Vec<String>,
    /// Whether the declared artifact set is complete. Incomplete evidence is
    /// permitted only for an already non-successful or unattempted route.
    pub artifact_capture: ArtifactCaptureStatus,
    /// Whether this result came from a child process or guard-skip synthesis.
    /// The default preserves decoding compatibility with older result JSON.
    #[serde(default)]
    pub disposition: RouteExecutionDisposition,
    /// Wall-clock duration in nanoseconds.
    pub duration_ns: u128,
    /// Where/how it ran.
    pub provenance: ExecutionProvenance,
}

impl OExecutionResult {
    /// Whether the process exited successfully with complete artifact evidence.
    pub fn succeeded(&self) -> bool {
        self.exit_code == Some(0) && self.artifact_capture.is_complete()
    }

    /// Whether guard policy synthesized this result without launching a child.
    pub fn was_guard_skipped(&self) -> bool {
        self.disposition == RouteExecutionDisposition::GuardSkipped
    }

    /// stdout decoded as UTF-8 (lossy).
    pub fn stdout_text(&self) -> String {
        String::from_utf8_lossy(&self.stdout).to_string()
    }

    /// stderr decoded as UTF-8 (lossy).
    pub fn stderr_text(&self) -> String {
        String::from_utf8_lossy(&self.stderr).to_string()
    }

    /// A compact, human-readable one-run summary.
    pub fn summary(&self) -> String {
        self.render_summary(true)
    }

    /// Human result rendering suitable for persistent unsigned observations.
    /// Foreign argv and host workspace paths are omitted because either may
    /// contain credentials or other ambient values. Captured process output,
    /// decoded values, and artifact evidence remain byte/evidence complete on
    /// the structured result stored alongside this rendering.
    pub fn observation_summary(&self) -> String {
        self.render_summary(false)
    }

    fn render_summary(&self, include_provenance: bool) -> String {
        let mut out = String::new();
        let status = match (self.disposition, self.exit_code) {
            (RouteExecutionDisposition::GuardSkipped, _) => "skipped".to_string(),
            (_, Some(0)) => "ok".to_string(),
            (_, Some(code)) => format!("exit {code}"),
            (_, None) => "no exit code".to_string(),
        };
        out.push_str(&format!(
            "route {} → {} ({} ms)\n",
            self.route_id,
            status,
            self.duration_ns / 1_000_000,
        ));
        if include_provenance {
            out.push_str(&format!(
                "  command: {}\n",
                self.provenance.command.join(" ")
            ));
            out.push_str(&format!("  cwd: {}\n", self.provenance.cwd.display()));
        }
        let stdout = self.stdout_text();
        if !stdout.trim().is_empty() {
            out.push_str("  stdout:\n");
            for line in stdout.lines() {
                out.push_str(&format!("    {line}\n"));
            }
        }
        if self.stdout_capture.truncated {
            let digest_prefix = self
                .stdout_capture
                .sha256
                .get(..self.stdout_capture.sha256.len().min(12))
                .unwrap_or("<invalid>");
            out.push_str(&format!(
                "  stdout truncated: retained {} of {} bytes (sha256:{})\n",
                self.stdout_capture.retained_bytes,
                self.stdout_capture.total_observed_bytes,
                digest_prefix,
            ));
        }
        let stderr = self.stderr_text();
        if !stderr.trim().is_empty() {
            out.push_str("  stderr:\n");
            for line in stderr.lines() {
                out.push_str(&format!("    {line}\n"));
            }
        }
        if self.stderr_capture.truncated {
            let digest_prefix = self
                .stderr_capture
                .sha256
                .get(..self.stderr_capture.sha256.len().min(12))
                .unwrap_or("<invalid>");
            out.push_str(&format!(
                "  stderr truncated: retained {} of {} bytes (sha256:{})\n",
                self.stderr_capture.retained_bytes,
                self.stderr_capture.total_observed_bytes,
                digest_prefix,
            ));
        }
        if let Some(value) = &self.value {
            out.push_str(&format!("  value: {value}\n"));
        }
        if !self.artifacts.is_empty() {
            out.push_str("  artifacts:\n");
            for artifact in &self.artifacts {
                out.push_str(&format!(
                    "    {} ({} bytes, sha256:{})\n",
                    artifact.path,
                    artifact.bytes_len,
                    &artifact.content_hash[..artifact.content_hash.len().min(12)],
                ));
            }
        }
        if let ArtifactCaptureStatus::Incomplete { failure } = &self.artifact_capture {
            out.push_str(&format!("  artifact evidence incomplete: {failure:?}\n"));
        }
        out
    }

    /// Render as a `serde_json::Value` (duration stored as a string so large
    /// nanosecond counts never overflow a JSON number).
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "route_id": self.route_id,
            "exit_code": self.exit_code,
            "succeeded": self.succeeded(),
            "stdout": self.stdout_text(),
            "stdout_capture": self.stdout_capture,
            "stderr": self.stderr_text(),
            "stderr_capture": self.stderr_capture,
            "value": self.value,
            "artifacts": self.artifacts,
            "artifact_requirements": self.artifact_requirements,
            "artifact_capture": self.artifact_capture,
            "disposition": self.disposition,
            "duration_ns": self.duration_ns.to_string(),
            "provenance": {
                "workspace": self.provenance.workspace.display().to_string(),
                "command": self.provenance.command,
                "cwd": self.provenance.cwd.display().to_string(),
            },
        })
    }
}
