//! Core project, route, and result types.
//!
//! Everything here is `serde`-serializable with deterministic ordering
//! (`BTreeMap` for keyed collections, `Vec` for ordered collections). These
//! types are the vocabulary shared by bundling, discovery, manifest parsing,
//! materialization, the route runtime, and the `.O` lowering.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::PathBuf;

/// The on-disk/on-wire format version of a [`ProjectBundle`].
pub const BUNDLE_FORMAT_VERSION: u32 = 1;

// ─────────────────────────────────────────────────────────────────────────────
// base64 helper for byte payloads inside JSON
// ─────────────────────────────────────────────────────────────────────────────

/// Serialize `Vec<u8>` as a base64 string so JSON bundles stay text-clean and
/// lossless for arbitrary binary assets.
pub(crate) mod b64_bytes {
    use base64::{engine::general_purpose::STANDARD as B64, Engine};
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S: Serializer>(bytes: &[u8], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&B64.encode(bytes))
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = String::deserialize(d)?;
        B64.decode(s.as_bytes()).map_err(serde::de::Error::custom)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Files
// ─────────────────────────────────────────────────────────────────────────────

/// The semantic role a stored file plays in the project.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum FileRole {
    /// Human-authored source in some language.
    Source,
    /// Binary or textual asset (data, images, fixtures, …).
    Asset,
    /// A build/config manifest (Cargo.toml, package.json, pyproject.toml, …).
    Manifest,
    /// Route metadata generated by O-lang tooling.
    GeneratedRouteMetadata,
    /// A file identified as a runnable entrypoint.
    Entrypoint,
    /// Anything else (empty files, extensionless files, unclassified).
    #[default]
    Other,
}

/// A single file captured losslessly inside a [`ProjectBundle`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProjectFile {
    /// Normalized, relative, `/`-separated path. Never absolute, never `..`.
    pub path: String,
    /// Raw file bytes. Serialized as base64 in JSON.
    #[serde(with = "b64_bytes")]
    pub bytes: Vec<u8>,
    /// Whether the executable bit is set (any of the unix exec bits).
    pub executable: bool,
    /// The full unix permission mode, when known.
    pub unix_mode: Option<u32>,
    /// If this entry is a symlink, its (relative, in-root) target.
    pub symlink_target: Option<String>,
    /// The O-lang backend/evaluator name inferred for this file, if any.
    pub evaluator: Option<String>,
    /// Lowercase hex sha256 of `bytes` (or of the link target for symlinks).
    pub content_hash: String,
    /// The semantic role of this file.
    pub role: FileRole,
}

impl ProjectFile {
    /// True when this entry represents a symbolic link rather than a regular
    /// file.
    pub fn is_symlink(&self) -> bool {
        self.symlink_target.is_some()
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Routes
// ─────────────────────────────────────────────────────────────────────────────

/// The broad category of a route, used for reporting and lowering.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum RouteKind {
    /// A language interpreter invoked with a script (e.g. `python3 main.py`).
    InterpreterCommand,
    /// A prebuilt native binary invoked directly.
    CompiledBinary,
    /// A build step that produces artifacts (e.g. `cargo build`).
    BuildTarget,
    /// A package-declared entrypoint (`[project.scripts]`, `bin`, …).
    PackageEntrypoint,
    /// A shell task / script runner target (npm scripts, Makefile targets).
    #[default]
    ShellTask,
    /// An O-lang evaluator block.
    OEvaluator,
    /// A composite route that sequences prerequisites into one logical run.
    Composite,
}

/// How the stdout of a route should be interpreted into a structured value.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum ResultCodec {
    /// Treat stdout as opaque UTF-8 text.
    #[default]
    Text,
    /// Parse stdout as JSON into `OExecutionResult.value`.
    Json,
    /// Treat stdout as raw bytes only.
    Bytes,
}

impl ResultCodec {
    /// Parse a manifest/CLI codec token. Unknown tokens fall back to `Text`.
    pub fn parse(token: &str) -> ResultCodec {
        match token.trim().to_ascii_lowercase().as_str() {
            "json" => ResultCodec::Json,
            "bytes" | "binary" | "blob" => ResultCodec::Bytes,
            _ => ResultCodec::Text,
        }
    }
}

/// A precondition that must hold before a route may run.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RouteGuard {
    /// The host OS (`std::env::consts::OS`) must equal this value.
    PlatformOs(String),
    /// The named command must be resolvable on `PATH`.
    CommandAvailable(String),
    /// The named environment variable must be set (non-empty).
    EnvVarSet(String),
}

/// Where a route came from — used for reporting and manifest-wins merging.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum RouteProvenance {
    /// Declared explicitly in the project manifest at `path`.
    Manifest { path: String },
    /// Auto-discovered by an ecosystem probe, with human-readable evidence.
    Discovered { ecosystem: String, evidence: String },
    /// Injected/overridden from the command line.
    CliOverride,
}

/// Declared read/write effects of a route. Resource keys are opaque strings
/// like `project:out/**`, `host:/tmp/x`, `env:PATH`, or `network`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct RouteEffects {
    /// The route is known to have no observable side effects.
    pub pure: bool,
    /// The route's effects are unknown / unconstrained (the safe default).
    pub unknown: bool,
    /// Resource keys the route reads.
    pub reads: Vec<String>,
    /// Resource keys the route writes.
    pub writes: Vec<String>,
}

impl RouteEffects {
    /// The conservative default: effects unknown.
    pub fn unknown() -> RouteEffects {
        RouteEffects {
            pure: false,
            unknown: true,
            reads: Vec::new(),
            writes: Vec::new(),
        }
    }
}

/// A single, concrete, runnable route through the project.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RouteSpec {
    /// Stable identifier, unique within a bundle.
    pub id: String,
    /// Human-readable label.
    pub label: String,
    /// Broad category.
    pub kind: RouteKind,
    /// The command vector: `command[0]` is the program, the rest are the fixed
    /// leading arguments. `arguments` are appended after these.
    pub command: Vec<String>,
    /// The O-lang evaluator name, when this route runs through one.
    pub evaluator: Option<String>,
    /// The primary entrypoint file (relative path), when applicable.
    pub entrypoint: Option<String>,
    /// Working directory, relative to the project root (`.` for the root).
    pub working_directory: String,
    /// Extra arguments appended to `command`.
    pub arguments: Vec<String>,
    /// Environment overlay applied when running.
    pub environment: BTreeMap<String, String>,
    /// Route ids that must run (in a shared workspace) before this one.
    pub prerequisites: Vec<String>,
    /// Declared input resource keys.
    pub inputs: Vec<String>,
    /// Declared output globs (relative), collected as artifacts after a run.
    pub outputs: Vec<String>,
    /// Declared effects.
    pub effects: RouteEffects,
    /// How to decode stdout.
    pub result_codec: ResultCodec,
    /// Capability tokens this route provides (used by route sets).
    pub provides: Vec<String>,
    /// Guards evaluated before running.
    pub guards: Vec<RouteGuard>,
    /// Selection priority; higher wins in fallback ordering.
    pub priority: i32,
    /// Whether this route is (a candidate for) the project default.
    pub is_default: bool,
    /// Where this route came from.
    pub provenance: RouteProvenance,
}

impl RouteSpec {
    /// Construct a minimal route with sensible defaults.
    pub fn new(id: impl Into<String>, provenance: RouteProvenance) -> RouteSpec {
        let id = id.into();
        RouteSpec {
            label: id.clone(),
            id,
            kind: RouteKind::default(),
            command: Vec::new(),
            evaluator: None,
            entrypoint: None,
            working_directory: ".".to_string(),
            arguments: Vec::new(),
            environment: BTreeMap::new(),
            prerequisites: Vec::new(),
            inputs: Vec::new(),
            outputs: Vec::new(),
            effects: RouteEffects::unknown(),
            result_codec: ResultCodec::Text,
            provides: Vec::new(),
            guards: Vec::new(),
            priority: 0,
            is_default: false,
            provenance,
        }
    }

    /// The full argument vector (`command` followed by `arguments`).
    pub fn full_command(&self) -> Vec<String> {
        let mut v = self.command.clone();
        v.extend(self.arguments.iter().cloned());
        v
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Route sets & policies
// ─────────────────────────────────────────────────────────────────────────────

/// The policy that decides which alternative(s) of a [`RouteSet`] execute.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub enum RoutePolicy {
    /// Run exactly the named route id.
    Explicit(String),
    /// Run the unambiguous default route.
    #[default]
    Default,
    /// Try alternatives in priority/declared order until one succeeds.
    Fallback,
    /// Run alternatives sequentially, returning the first success.
    AnySuccess,
    /// Race alternatives in parallel, return the first success and cancel
    /// the losers cooperatively.
    RaceSuccess,
    /// Race alternatives in parallel, return the first to settle (success or
    /// failure) and cancel the losers cooperatively.
    RaceSettle,
    /// Run every alternative (each in its own isolated workspace).
    All,
    /// Run all in parallel and verify their results are equivalent
    /// (JSON values when decoded, trimmed stdout otherwise).
    VerifyEquivalent,
    /// Run all in parallel and select the fastest successful alternative.
    BenchmarkAndSelect,
}

impl RoutePolicy {
    /// Parse a policy token as used in the manifest / CLI.
    ///
    /// `explicit` requires the route id to be supplied separately (via
    /// `explicit_id`); when absent it degrades to [`RoutePolicy::Default`]
    /// unless the token itself carries it as `explicit:<id>`.
    pub fn parse(token: &str) -> RoutePolicy {
        let token = token.trim();
        if let Some(rest) = token.strip_prefix("explicit:") {
            return RoutePolicy::Explicit(rest.trim().to_string());
        }
        match token.to_ascii_lowercase().as_str() {
            "explicit" => RoutePolicy::Explicit(String::new()),
            "default" => RoutePolicy::Default,
            "fallback" => RoutePolicy::Fallback,
            "any_success" | "anysuccess" | "any" => RoutePolicy::AnySuccess,
            "race_success" | "racesuccess" | "race" => RoutePolicy::RaceSuccess,
            "race_settle" | "racesettle" => RoutePolicy::RaceSettle,
            "all" => RoutePolicy::All,
            "verify_equivalent" | "verifyequivalent" | "verify" => RoutePolicy::VerifyEquivalent,
            "benchmark_and_select" | "benchmarkandselect" | "benchmark" => {
                RoutePolicy::BenchmarkAndSelect
            }
            _ => RoutePolicy::Default,
        }
    }

    /// A short human-readable token for this policy.
    pub fn token(&self) -> String {
        match self {
            RoutePolicy::Explicit(id) if id.is_empty() => "explicit".to_string(),
            RoutePolicy::Explicit(id) => format!("explicit:{id}"),
            RoutePolicy::Default => "default".to_string(),
            RoutePolicy::Fallback => "fallback".to_string(),
            RoutePolicy::AnySuccess => "any_success".to_string(),
            RoutePolicy::RaceSuccess => "race_success".to_string(),
            RoutePolicy::RaceSettle => "race_settle".to_string(),
            RoutePolicy::All => "all".to_string(),
            RoutePolicy::VerifyEquivalent => "verify_equivalent".to_string(),
            RoutePolicy::BenchmarkAndSelect => "benchmark_and_select".to_string(),
        }
    }

    /// Whether the route runtime can currently execute this policy.
    /// Every represented policy is now executable.
    pub fn is_executable(&self) -> bool {
        true
    }
}

/// A named set of alternative routes providing the same capability.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RouteSet {
    /// The capability token these routes provide.
    pub provides: String,
    /// Candidate route ids, in declared order.
    pub alternatives: Vec<String>,
    /// How to select among the alternatives.
    pub policy: RoutePolicy,
}

// ─────────────────────────────────────────────────────────────────────────────
// The bundle
// ─────────────────────────────────────────────────────────────────────────────

/// A lossless, route-preserving snapshot of an entire project.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProjectBundle {
    /// Format version (see [`BUNDLE_FORMAT_VERSION`]).
    pub format_version: u32,
    /// Project name.
    pub name: String,
    /// Deterministic fingerprint of the whole file tree.
    pub root_fingerprint: String,
    /// All captured files, in sorted path order.
    pub files: Vec<ProjectFile>,
    /// All routes, both discovered and manifest-declared.
    pub routes: Vec<RouteSpec>,
    /// Route sets grouping alternative routes by capability.
    pub route_sets: Vec<RouteSet>,
    /// The chosen default route id, if unambiguous.
    pub default_route: Option<String>,
    /// Free-form metadata.
    pub metadata: BTreeMap<String, String>,
}

impl ProjectBundle {
    /// An empty bundle with the given name.
    pub fn empty(name: impl Into<String>) -> ProjectBundle {
        ProjectBundle {
            format_version: BUNDLE_FORMAT_VERSION,
            name: name.into(),
            root_fingerprint: String::new(),
            files: Vec::new(),
            routes: Vec::new(),
            route_sets: Vec::new(),
            default_route: None,
            metadata: BTreeMap::new(),
        }
    }

    /// Look up a route by id.
    pub fn route(&self, id: &str) -> Option<&RouteSpec> {
        self.routes.iter().find(|r| r.id == id)
    }

    /// Look up a route set by its `provides` capability token.
    pub fn route_set(&self, provides: &str) -> Option<&RouteSet> {
        self.route_sets.iter().find(|s| s.provides == provides)
    }

    /// Route ids marked `is_default`.
    pub fn default_candidates(&self) -> Vec<&RouteSpec> {
        self.routes.iter().filter(|r| r.is_default).collect()
    }

    /// Resolve the effective default route id, preferring `default_route`,
    /// then a single `is_default` candidate. Returns `None` when ambiguous or
    /// absent.
    pub fn resolved_default(&self) -> Option<String> {
        if let Some(id) = &self.default_route {
            if self.route(id).is_some() {
                return Some(id.clone());
            }
        }
        let candidates = self.default_candidates();
        if candidates.len() == 1 {
            return Some(candidates[0].id.clone());
        }
        None
    }

    /// Render the route table as human-readable text (no execution).
    pub fn route_table(&self) -> String {
        let mut out = String::new();
        let default = self.resolved_default();
        out.push_str(&format!(
            "Project: {}  ({} route{}, {} route set{})\n",
            self.name,
            self.routes.len(),
            if self.routes.len() == 1 { "" } else { "s" },
            self.route_sets.len(),
            if self.route_sets.len() == 1 { "" } else { "s" },
        ));
        if self.routes.is_empty() {
            out.push_str("  (no routes)\n");
        }
        for route in &self.routes {
            let is_default = default.as_deref() == Some(route.id.as_str());
            let marker = if is_default { "*" } else { " " };
            let provenance = match &route.provenance {
                RouteProvenance::Manifest { path } => format!("manifest:{path}"),
                RouteProvenance::Discovered { ecosystem, .. } => {
                    format!("discovered:{ecosystem}")
                }
                RouteProvenance::CliOverride => "cli".to_string(),
            };
            let command = route.full_command().join(" ");
            out.push_str(&format!(
                "{marker} {id}  [{kind:?}]  provides={provides}  {provenance}\n      $ {command}\n",
                id = route.id,
                kind = route.kind,
                provides = if route.provides.is_empty() {
                    "-".to_string()
                } else {
                    route.provides.join(",")
                },
            ));
        }
        for set in &self.route_sets {
            out.push_str(&format!(
                "  set provides={} policy={} alternatives=[{}]\n",
                set.provides,
                set.policy.token(),
                set.alternatives.join(", "),
            ));
        }
        if default.is_none() && !self.routes.is_empty() {
            out.push_str("  (no unambiguous default route — select one with --route)\n");
        }
        out
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Execution results
// ─────────────────────────────────────────────────────────────────────────────

/// A produced output artifact collected after a route runs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Artifact {
    /// Path relative to the execution workspace.
    pub path: String,
    /// Lowercase hex sha256 of the artifact bytes.
    pub content_hash: String,
    /// Length of the artifact in bytes.
    pub bytes_len: u64,
}

/// Provenance of a single execution — where and how it ran.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExecutionProvenance {
    /// The workspace directory the route ran in.
    pub workspace: PathBuf,
    /// The full command vector that was spawned.
    pub command: Vec<String>,
    /// The working directory the command ran in.
    pub cwd: PathBuf,
}

/// The result of running one route.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OExecutionResult {
    /// The route id that produced this result.
    pub route_id: String,
    /// Process exit code, if the process ran to completion.
    pub exit_code: Option<i32>,
    /// Captured stdout bytes.
    #[serde(with = "b64_bytes")]
    pub stdout: Vec<u8>,
    /// Captured stderr bytes.
    #[serde(with = "b64_bytes")]
    pub stderr: Vec<u8>,
    /// Decoded structured value (only for `ResultCodec::Json`).
    pub value: Option<serde_json::Value>,
    /// Collected output artifacts.
    pub artifacts: Vec<Artifact>,
    /// Wall-clock duration in nanoseconds.
    pub duration_ns: u128,
    /// Where/how it ran.
    pub provenance: ExecutionProvenance,
}

impl OExecutionResult {
    /// Whether the process exited successfully (exit code 0).
    pub fn succeeded(&self) -> bool {
        self.exit_code == Some(0)
    }

    /// stdout decoded as UTF-8 (lossy).
    pub fn stdout_text(&self) -> String {
        String::from_utf8_lossy(&self.stdout).to_string()
    }

    /// stderr decoded as UTF-8 (lossy).
    pub fn stderr_text(&self) -> String {
        String::from_utf8_lossy(&self.stderr).to_string()
    }

    /// A compact, human-readable one-run summary.
    pub fn summary(&self) -> String {
        let mut out = String::new();
        let status = match self.exit_code {
            Some(0) => "ok".to_string(),
            Some(code) => format!("exit {code}"),
            None => "no exit code".to_string(),
        };
        out.push_str(&format!(
            "route {} → {} ({} ms)\n",
            self.route_id,
            status,
            self.duration_ns / 1_000_000,
        ));
        out.push_str(&format!(
            "  command: {}\n",
            self.provenance.command.join(" ")
        ));
        out.push_str(&format!("  cwd: {}\n", self.provenance.cwd.display()));
        let stdout = self.stdout_text();
        if !stdout.trim().is_empty() {
            out.push_str("  stdout:\n");
            for line in stdout.lines() {
                out.push_str(&format!("    {line}\n"));
            }
        }
        let stderr = self.stderr_text();
        if !stderr.trim().is_empty() {
            out.push_str("  stderr:\n");
            for line in stderr.lines() {
                out.push_str(&format!("    {line}\n"));
            }
        }
        if let Some(value) = &self.value {
            out.push_str(&format!("  value: {value}\n"));
        }
        if !self.artifacts.is_empty() {
            out.push_str("  artifacts:\n");
            for artifact in &self.artifacts {
                out.push_str(&format!(
                    "    {} ({} bytes, sha256:{})\n",
                    artifact.path,
                    artifact.bytes_len,
                    &artifact.content_hash[..artifact.content_hash.len().min(12)],
                ));
            }
        }
        out
    }

    /// Render as a `serde_json::Value` (duration stored as a string so large
    /// nanosecond counts never overflow a JSON number).
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "route_id": self.route_id,
            "exit_code": self.exit_code,
            "succeeded": self.succeeded(),
            "stdout": self.stdout_text(),
            "stderr": self.stderr_text(),
            "value": self.value,
            "artifacts": self.artifacts,
            "duration_ns": self.duration_ns.to_string(),
            "provenance": {
                "workspace": self.provenance.workspace.display().to_string(),
                "command": self.provenance.command,
                "cwd": self.provenance.cwd.display().to_string(),
            },
        })
    }
}
