#!/usr/bin/env python3
"""Build and inspect deterministic OSTADIX GPT boot-media containers.

This tool deliberately owns only the outer GPT container.  A platform media
builder supplies a complete EFI System Partition image, and this module binds
those exact bytes into a reproducible disk layout with deterministic UUIDs.
It does not write physical devices.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import stat
import struct
import sys
import uuid
import zlib


SCHEMA = "ostadix.boot-media/v1"
TARGET_PLAN_SCHEMA = "ostadix.boot-media-target-plan/v2"
SECTOR_SIZE = 512
PARTITION_ENTRY_COUNT = 128
PARTITION_ENTRY_SIZE = 128
PARTITION_TABLE_BYTES = PARTITION_ENTRY_COUNT * PARTITION_ENTRY_SIZE
PARTITION_TABLE_SECTORS = PARTITION_TABLE_BYTES // SECTOR_SIZE
ESP_START_LBA = 2048
TAIL_GAP_SECTORS = 2048
MAX_ESP_BYTES = 512 * 1024 * 1024
MAX_IMAGE_BYTES = (
    ESP_START_LBA + MAX_ESP_BYTES // SECTOR_SIZE + TAIL_GAP_SECTORS
) * SECTOR_SIZE
# OSTADIX Alpha intentionally bounds target-layout arithmetic and confirmation
# work even though GPT's 64-bit fields can describe much larger media.  The
# plan itself remains constant-space at this limit; no target-sized allocation
# is performed.
MAX_TARGET_BYTES = 16 * 1024 * 1024 * 1024 * 1024
GPT_SIGNATURE = b"EFI PART"
GPT_REVISION = 0x0001_0000
GPT_HEADER_SIZE = 92
PROTECTIVE_MBR_TYPE = 0xEE
ESP_TYPE_GUID = uuid.UUID("c12a7328-f81f-11d2-ba4b-00a0c93ec93b")
OSTADIX_MEDIA_NAMESPACE = uuid.UUID("bf9adb46-c30e-5cc0-94ec-a28553635412")
TARGET_PLAN_DOMAIN = b"OSTADIX/BOOT-MEDIA-TARGET-PLAN/V2\0"
UNWRITTEN_POLICY = "preserve-unhashed-unverified-may-be-recoverable"


class MediaError(ValueError):
    """The supplied media container is malformed or outside bounded v1."""


@dataclass(frozen=True)
class PlannedExtent:
    """One non-overlapping byte range admitted for target mutation.

    An extent is either copied from the immutable canonical source image or
    generated by the target planner.  ``data`` is deliberately excluded from
    the public form; its SHA-256 is the evidence used by the writer and by the
    confirmation token.
    """

    kind: str
    target_offset: int
    bytes: int
    sha256: str
    source_offset: int | None = None
    data: bytes | None = None

    def public(self) -> dict[str, object]:
        result: dict[str, object] = {
            "kind": self.kind,
            "target_offset": self.target_offset,
            "bytes": self.bytes,
            "sha256": self.sha256,
        }
        if self.source_offset is not None:
            result["source_offset"] = self.source_offset
        else:
            result["generated"] = True
        return result


@dataclass(frozen=True)
class TargetMediaPlan:
    """Capacity-bound sparse target image plan.

    ``target_plan_sha256`` commits to the target capacity and ordered extent
    descriptors/data hashes. It is not an image digest and makes no claim
    about recoverable old bytes in explicitly unwritten ranges.
    """

    source_sha256: str
    source_bytes: int
    target_bytes: int
    disk_guid: str
    partition_guid: str
    esp_sha256: str
    esp_bytes: int
    esp_first_lba: int
    esp_last_lba: int
    target_last_usable_lba: int
    target_backup_entries_lba: int
    target_backup_header_lba: int
    extents: tuple[PlannedExtent, ...]
    unwritten_ranges: tuple[tuple[int, int], ...]
    target_plan_sha256: str
    target_image_sha256: str | None

    def public(self) -> dict[str, object]:
        return {
            "schema": TARGET_PLAN_SCHEMA,
            "source_sha256": self.source_sha256,
            "source_bytes": self.source_bytes,
            "target_bytes": self.target_bytes,
            "target_plan_sha256": self.target_plan_sha256,
            "target_image_sha256": self.target_image_sha256,
            "disk_guid": self.disk_guid,
            "partition_guid": self.partition_guid,
            "esp_sha256": self.esp_sha256,
            "esp_bytes": self.esp_bytes,
            "esp_first_lba": self.esp_first_lba,
            "esp_last_lba": self.esp_last_lba,
            "sector_size": SECTOR_SIZE,
            "target_last_usable_lba": self.target_last_usable_lba,
            "target_backup_entries_lba": self.target_backup_entries_lba,
            "target_backup_header_lba": self.target_backup_header_lba,
            "extents": [extent.public() for extent in self.extents],
            "unwritten_policy": UNWRITTEN_POLICY,
            "unwritten_ranges": [
                {"offset": offset, "bytes": size}
                for offset, size in self.unwritten_ranges
            ],
        }


def _sha256(data: object) -> str:
    return hashlib.sha256(data).hexdigest()


def _file_identity(value: os.stat_result) -> tuple[int, int, int, int, int]:
    return (
        value.st_dev,
        value.st_ino,
        value.st_size,
        value.st_mtime_ns,
        value.st_ctime_ns,
    )


def _read_bounded(path: Path, maximum: int) -> bytes:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise MediaError(
            f"cannot open bounded input without following links: {path}: {error}"
        ) from error
    try:
        stream = os.fdopen(descriptor, "rb")
    except OSError as error:
        try:
            os.close(descriptor)
        except OSError:
            pass
        raise MediaError(f"cannot attach bounded input descriptor: {path}: {error}") from error
    try:
        with stream:
            before = os.fstat(stream.fileno())
            if not stat.S_ISREG(before.st_mode):
                raise MediaError(f"not a regular file: {path}")
            size = before.st_size
            if size <= 0 or size > maximum:
                raise MediaError(f"file size outside 1..{maximum} bytes: {path}")
            chunks: list[bytes] = []
            remaining = size
            while remaining:
                chunk = stream.read(min(4 * 1024 * 1024, remaining))
                if not chunk:
                    raise MediaError(f"file ended before its admitted size: {path}")
                chunks.append(chunk)
                remaining -= len(chunk)
            if stream.read(1):
                raise MediaError(f"file grew beyond its admitted size: {path}")
            after = os.fstat(stream.fileno())
    except MediaError:
        raise
    except OSError as error:
        raise MediaError(f"cannot read bounded input {path}: {error}") from error

    if _file_identity(after) != _file_identity(before):
        raise MediaError(f"file changed while it was read: {path}")
    try:
        current = os.stat(path, follow_symlinks=False)
    except OSError as error:
        raise MediaError(f"input path changed after it was read: {path}: {error}") from error
    if not stat.S_ISREG(current.st_mode) or _file_identity(current) != _file_identity(
        before
    ):
        raise MediaError(f"input path was replaced while it was read: {path}")
    return b"".join(chunks)


def _derived_uuid(kind: str, digest: str) -> uuid.UUID:
    return uuid.uuid5(OSTADIX_MEDIA_NAMESPACE, f"{kind}:{digest}")


def _partition_entry(first_lba: int, last_lba: int, unique: uuid.UUID) -> bytes:
    name = "OSTADIX".encode("utf-16-le")
    if len(name) > 72:
        raise AssertionError("partition name exceeds GPT field")
    return b"".join(
        (
            ESP_TYPE_GUID.bytes_le,
            unique.bytes_le,
            struct.pack("<QQQ", first_lba, last_lba, 0),
            name.ljust(72, b"\0"),
        )
    )


def _gpt_header(
    *,
    current_lba: int,
    backup_lba: int,
    first_usable: int,
    last_usable: int,
    disk_guid: uuid.UUID,
    entries_lba: int,
    entries_crc: int,
) -> bytes:
    header = bytearray(SECTOR_SIZE)
    struct.pack_into(
        "<8sIIIIQQQQ16sQIII",
        header,
        0,
        GPT_SIGNATURE,
        GPT_REVISION,
        GPT_HEADER_SIZE,
        0,
        0,
        current_lba,
        backup_lba,
        first_usable,
        last_usable,
        disk_guid.bytes_le,
        entries_lba,
        PARTITION_ENTRY_COUNT,
        PARTITION_ENTRY_SIZE,
        entries_crc,
    )
    crc = zlib.crc32(header[:GPT_HEADER_SIZE]) & 0xFFFF_FFFF
    struct.pack_into("<I", header, 16, crc)
    return bytes(header)


def _protective_mbr(total_sectors: int) -> bytes:
    if total_sectors <= 1:
        raise MediaError("target contains too few sectors for a protective MBR")
    mbr = bytearray(SECTOR_SIZE)
    mbr[510:512] = b"\x55\xaa"
    mbr_size = min(total_sectors - 1, 0xFFFF_FFFF)
    struct.pack_into(
        "<B3sB3sII",
        mbr,
        446,
        0,
        b"\0\x02\0",
        PROTECTIVE_MBR_TYPE,
        b"\xff\xff\xff",
        1,
        mbr_size,
    )
    return bytes(mbr)


def build_image(esp: bytes) -> tuple[bytes, dict[str, object]]:
    if not esp or len(esp) > MAX_ESP_BYTES:
        raise MediaError(f"ESP size must be within 1..{MAX_ESP_BYTES} bytes")
    if len(esp) % SECTOR_SIZE != 0:
        raise MediaError("ESP image size must be a multiple of 512 bytes")

    esp_digest = _sha256(esp)
    disk_guid = _derived_uuid("disk", esp_digest)
    partition_guid = _derived_uuid("esp", esp_digest)
    esp_sectors = len(esp) // SECTOR_SIZE
    esp_last_lba = ESP_START_LBA + esp_sectors - 1
    total_sectors = ESP_START_LBA + esp_sectors + TAIL_GAP_SECTORS
    backup_header_lba = total_sectors - 1
    backup_entries_lba = backup_header_lba - PARTITION_TABLE_SECTORS
    first_usable = 2 + PARTITION_TABLE_SECTORS
    last_usable = backup_entries_lba - 1
    if esp_last_lba > last_usable:
        raise AssertionError("ESP overlaps backup GPT table")

    entries = bytearray(PARTITION_TABLE_BYTES)
    entry = _partition_entry(ESP_START_LBA, esp_last_lba, partition_guid)
    entries[: len(entry)] = entry
    entries_crc = zlib.crc32(entries) & 0xFFFF_FFFF

    primary_header = _gpt_header(
        current_lba=1,
        backup_lba=backup_header_lba,
        first_usable=first_usable,
        last_usable=last_usable,
        disk_guid=disk_guid,
        entries_lba=2,
        entries_crc=entries_crc,
    )
    backup_header = _gpt_header(
        current_lba=backup_header_lba,
        backup_lba=1,
        first_usable=first_usable,
        last_usable=last_usable,
        disk_guid=disk_guid,
        entries_lba=backup_entries_lba,
        entries_crc=entries_crc,
    )

    image = bytearray(total_sectors * SECTOR_SIZE)
    image[:SECTOR_SIZE] = _protective_mbr(total_sectors)
    image[SECTOR_SIZE : 2 * SECTOR_SIZE] = primary_header
    image[2 * SECTOR_SIZE : 2 * SECTOR_SIZE + len(entries)] = entries
    esp_offset = ESP_START_LBA * SECTOR_SIZE
    image[esp_offset : esp_offset + len(esp)] = esp
    backup_entries_offset = backup_entries_lba * SECTOR_SIZE
    image[backup_entries_offset : backup_entries_offset + len(entries)] = entries
    backup_header_offset = backup_header_lba * SECTOR_SIZE
    image[backup_header_offset : backup_header_offset + SECTOR_SIZE] = backup_header

    data = bytes(image)
    metadata: dict[str, object] = {
        "schema": SCHEMA,
        "bytes": len(data),
        "sha256": _sha256(data),
        "disk_guid": str(disk_guid),
        "partition_guid": str(partition_guid),
        "esp_sha256": esp_digest,
        "esp_bytes": len(esp),
        "esp_first_lba": ESP_START_LBA,
        "esp_last_lba": esp_last_lba,
        "sector_size": SECTOR_SIZE,
    }
    return data, metadata


def _validated_header(image: bytes, lba: int) -> dict[str, object]:
    offset = lba * SECTOR_SIZE
    if offset + SECTOR_SIZE > len(image):
        raise MediaError("GPT header lies outside image")
    sector = image[offset : offset + SECTOR_SIZE]
    if sector[:8] != GPT_SIGNATURE:
        raise MediaError(f"missing GPT signature at LBA {lba}")
    revision, size, stored_crc, reserved = struct.unpack_from("<IIII", sector, 8)
    if revision != GPT_REVISION or size != GPT_HEADER_SIZE or reserved != 0:
        raise MediaError("unsupported GPT header revision, size, or reserved field")
    if any(sector[size:]):
        raise MediaError(f"GPT header reserved tail is not zero at LBA {lba}")
    header = bytearray(sector[:size])
    struct.pack_into("<I", header, 16, 0)
    if zlib.crc32(header) & 0xFFFF_FFFF != stored_crc:
        raise MediaError(f"GPT header CRC mismatch at LBA {lba}")
    current, backup, first, last = struct.unpack_from("<QQQQ", sector, 24)
    if current != lba or backup >= len(image) // SECTOR_SIZE or first > last:
        raise MediaError("invalid GPT header topology")
    disk_guid = uuid.UUID(bytes_le=sector[56:72])
    entries_lba, count, entry_size, entries_crc = struct.unpack_from("<QIII", sector, 72)
    if count != PARTITION_ENTRY_COUNT or entry_size != PARTITION_ENTRY_SIZE:
        raise MediaError("unsupported GPT partition-table geometry")
    entries_offset = entries_lba * SECTOR_SIZE
    entries_end = entries_offset + PARTITION_TABLE_BYTES
    if entries_end > len(image):
        raise MediaError("GPT partition table lies outside image")
    entries = image[entries_offset:entries_end]
    if zlib.crc32(entries) & 0xFFFF_FFFF != entries_crc:
        raise MediaError("GPT partition-table CRC mismatch")
    return {
        "current": current,
        "backup": backup,
        "first_usable": first,
        "last_usable": last,
        "disk_guid": disk_guid,
        "entries_lba": entries_lba,
        "entries": entries,
    }


def inspect_image(image: bytes) -> dict[str, object]:
    minimum = (ESP_START_LBA + PARTITION_TABLE_SECTORS + 2) * SECTOR_SIZE
    if len(image) < minimum or len(image) % SECTOR_SIZE != 0:
        raise MediaError("image is too small or not sector aligned")
    if image[510:512] != b"\x55\xaa":
        raise MediaError("missing protective MBR")

    sectors = len(image) // SECTOR_SIZE
    boot, first_chs, kind, last_chs, first_mbr_lba, mbr_sectors = struct.unpack_from(
        "<B3sB3sII", image, 446
    )
    expected_mbr_sectors = min(sectors - 1, 0xFFFF_FFFF)
    if (
        boot != 0
        or first_chs != b"\0\x02\0"
        or kind != PROTECTIVE_MBR_TYPE
        or last_chs != b"\xff\xff\xff"
        or first_mbr_lba != 1
        or mbr_sectors != expected_mbr_sectors
        or any(image[462:510])
    ):
        raise MediaError("invalid protective MBR topology")
    if any(image[:446]):
        raise MediaError("protective MBR reserved region is not zero")

    primary = _validated_header(image, 1)
    backup = _validated_header(image, sectors - 1)
    if primary["backup"] != sectors - 1 or backup["backup"] != 1:
        raise MediaError("primary and backup GPT headers do not mirror each other")
    if primary["disk_guid"] != backup["disk_guid"] or primary["entries"] != backup["entries"]:
        raise MediaError("primary and backup GPT metadata differ")
    if (
        primary["entries_lba"] != 2
        or backup["entries_lba"] != sectors - 1 - PARTITION_TABLE_SECTORS
        or primary["first_usable"] != 2 + PARTITION_TABLE_SECTORS
        or backup["first_usable"] != primary["first_usable"]
        or primary["last_usable"] != sectors - 2 - PARTITION_TABLE_SECTORS
        or backup["last_usable"] != primary["last_usable"]
    ):
        raise MediaError("GPT geometry differs from bounded OSTADIX v1")

    entry = primary["entries"][:PARTITION_ENTRY_SIZE]
    if uuid.UUID(bytes_le=entry[:16]) != ESP_TYPE_GUID:
        raise MediaError("first partition is not an EFI System Partition")
    partition_guid = uuid.UUID(bytes_le=entry[16:32])
    first_lba, last_lba, attributes = struct.unpack_from("<QQQ", entry, 32)
    if attributes != 0 or first_lba != ESP_START_LBA or last_lba < first_lba:
        raise MediaError("invalid OSTADIX ESP range or attributes")
    if last_lba > int(primary["last_usable"]):
        raise MediaError("ESP extends beyond usable GPT range")
    if sectors != last_lba + 1 + TAIL_GAP_SECTORS:
        raise MediaError("disk tail geometry differs from bounded OSTADIX v1")
    if any(primary["entries"][PARTITION_ENTRY_SIZE:]):
        raise MediaError("OSTADIX v1 admits exactly one partition")
    expected_name = "OSTADIX".encode("utf-16-le").ljust(72, b"\0")
    if entry[56:] != expected_name:
        raise MediaError("OSTADIX ESP partition name or padding differs from bounded v1")

    esp_offset = first_lba * SECTOR_SIZE
    esp_end = (last_lba + 1) * SECTOR_SIZE
    primary_entries_end = (2 + PARTITION_TABLE_SECTORS) * SECTOR_SIZE
    if any(image[primary_entries_end:esp_offset]):
        raise MediaError("pre-ESP reserved padding is not zero")
    backup_entries_offset = int(backup["entries_lba"]) * SECTOR_SIZE
    if any(image[esp_end:backup_entries_offset]):
        raise MediaError("post-ESP reserved tail is not zero")
    image_view = memoryview(image)
    esp = image_view[esp_offset:esp_end]
    try:
        if len(esp) < 512 or bytes(esp[510:512]) != b"\x55\xaa":
            raise MediaError("ESP does not contain a FAT-compatible boot signature")
        esp_bytes = len(esp)
        esp_digest = _sha256(esp)
    finally:
        esp.release()
        image_view.release()
    disk_guid = primary["disk_guid"]
    if disk_guid != _derived_uuid("disk", esp_digest):
        raise MediaError("disk GUID is not bound to the ESP digest")
    if partition_guid != _derived_uuid("esp", esp_digest):
        raise MediaError("partition GUID is not bound to the ESP digest")

    return {
        "schema": SCHEMA,
        "bytes": len(image),
        "sha256": _sha256(image),
        "disk_guid": str(disk_guid),
        "partition_guid": str(partition_guid),
        "esp_sha256": esp_digest,
        "esp_bytes": esp_bytes,
        "esp_first_lba": first_lba,
        "esp_last_lba": last_lba,
        "sector_size": SECTOR_SIZE,
    }


def _generated_extent(kind: str, target_offset: int, data: bytes) -> PlannedExtent:
    return PlannedExtent(
        kind=kind,
        target_offset=target_offset,
        bytes=len(data),
        sha256=_sha256(data),
        data=data,
    )


def _source_extent(
    kind: str,
    target_offset: int,
    source_offset: int,
    size: int,
    image: object,
) -> PlannedExtent:
    view = memoryview(image)
    content = view[source_offset : source_offset + size]
    try:
        digest = _sha256(content)
    finally:
        content.release()
        view.release()
    return PlannedExtent(
        kind=kind,
        target_offset=target_offset,
        bytes=size,
        sha256=digest,
        source_offset=source_offset,
    )


def _validate_extents(
    extents: tuple[PlannedExtent, ...], *, source_bytes: int, target_bytes: int
) -> None:
    cursor = 0
    for extent in extents:
        if extent.bytes <= 0:
            raise MediaError(f"target extent {extent.kind!r} is empty")
        if (
            extent.target_offset % SECTOR_SIZE != 0
            or extent.bytes % SECTOR_SIZE != 0
        ):
            raise MediaError(f"target extent {extent.kind!r} is not sector aligned")
        if extent.target_offset < cursor:
            raise MediaError("target plan contains overlapping or unordered extents")
        extent_end = extent.target_offset + extent.bytes
        if extent_end > target_bytes:
            raise MediaError(f"target extent {extent.kind!r} exceeds target capacity")
        if (extent.source_offset is None) == (extent.data is None):
            raise MediaError(
                f"target extent {extent.kind!r} must have exactly one data source"
            )
        if extent.source_offset is not None:
            if (
                extent.source_offset < 0
                or extent.source_offset + extent.bytes > source_bytes
            ):
                raise MediaError(f"target extent {extent.kind!r} exceeds source image")
        else:
            assert extent.data is not None
            if len(extent.data) != extent.bytes or _sha256(extent.data) != extent.sha256:
                raise MediaError(f"generated target extent {extent.kind!r} is inconsistent")
        if not _is_sha256(extent.sha256):
            raise MediaError(f"target extent {extent.kind!r} has an invalid SHA-256")
        cursor = extent_end


def _is_sha256(value: str) -> bool:
    return len(value) == 64 and all(character in "0123456789abcdef" for character in value)


def _unwritten_ranges(
    extents: tuple[PlannedExtent, ...], target_bytes: int
) -> tuple[tuple[int, int], ...]:
    result: list[tuple[int, int]] = []
    cursor = 0
    for extent in extents:
        if extent.target_offset > cursor:
            result.append((cursor, extent.target_offset - cursor))
        cursor = extent.target_offset + extent.bytes
    if cursor < target_bytes:
        result.append((cursor, target_bytes - cursor))
    return tuple(result)


def _target_plan_commitment(document: dict[str, object]) -> str:
    encoded = json.dumps(document, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(TARGET_PLAN_DOMAIN + encoded).hexdigest()


def _fully_defined_target_sha256(
    image: object,
    extents: tuple[PlannedExtent, ...],
    unwritten: tuple[tuple[int, int], ...],
) -> str | None:
    """Hash the physical target only when every byte is defined by the plan."""
    if unwritten:
        return None
    digest = hashlib.sha256()
    source_view = memoryview(image)
    try:
        for extent in extents:
            if extent.source_offset is not None:
                content = source_view[
                    extent.source_offset : extent.source_offset + extent.bytes
                ]
                try:
                    digest.update(content)
                finally:
                    content.release()
            else:
                assert extent.data is not None
                digest.update(extent.data)
    finally:
        source_view.release()
    return digest.hexdigest()


def plan_target_image(image: object, target_bytes: int) -> TargetMediaPlan:
    """Derive a deterministic sparse write plan for one exact target capacity.

    ``image`` must remain a canonical ``ostadix.boot-media/v1`` container;
    target planning never relaxes source inspection.  A larger target keeps
    the partition and ESP bytes fixed, updates the protective MBR and both GPT
    headers for the final LBA, retires any now-stale source backup GPT bytes,
    and leaves only explicitly reported ``unwritten_ranges`` untouched. Old
    bytes in those ranges may remain recoverable and are neither hashed nor
    read-back verified.
    """

    metadata = inspect_image(image)  # canonical source validation is mandatory
    source_bytes = len(image)
    if target_bytes % SECTOR_SIZE != 0:
        raise MediaError("target capacity must be a multiple of 512 bytes")
    if target_bytes < source_bytes:
        raise MediaError(
            f"target capacity is smaller than the canonical image "
            f"(target={target_bytes}, source={source_bytes})"
        )
    if target_bytes > MAX_TARGET_BYTES:
        raise MediaError(
            f"target capacity exceeds bounded OSTADIX Alpha maximum {MAX_TARGET_BYTES}"
        )

    target_sectors = target_bytes // SECTOR_SIZE
    backup_header_lba = target_sectors - 1
    backup_entries_lba = backup_header_lba - PARTITION_TABLE_SECTORS
    first_usable = 2 + PARTITION_TABLE_SECTORS
    last_usable = backup_entries_lba - 1
    esp_last_lba = int(metadata["esp_last_lba"])
    if esp_last_lba > last_usable:
        raise MediaError("target capacity leaves no room for the admitted ESP and backup GPT")

    primary_entries_offset = 2 * SECTOR_SIZE
    entries = bytes(
        image[
            primary_entries_offset : primary_entries_offset + PARTITION_TABLE_BYTES
        ]
    )
    entries_crc = zlib.crc32(entries) & 0xFFFF_FFFF
    disk_guid = uuid.UUID(str(metadata["disk_guid"]))
    primary_header = _gpt_header(
        current_lba=1,
        backup_lba=backup_header_lba,
        first_usable=first_usable,
        last_usable=last_usable,
        disk_guid=disk_guid,
        entries_lba=2,
        entries_crc=entries_crc,
    )
    backup_header = _gpt_header(
        current_lba=backup_header_lba,
        backup_lba=1,
        first_usable=first_usable,
        last_usable=last_usable,
        disk_guid=disk_guid,
        entries_lba=backup_entries_lba,
        entries_crc=entries_crc,
    )

    primary_data = _protective_mbr(target_sectors) + primary_header + entries
    primary_bytes = (2 + PARTITION_TABLE_SECTORS) * SECTOR_SIZE
    if len(primary_data) != primary_bytes:
        raise AssertionError("primary GPT extent has unexpected size")
    source_backup_offset = source_bytes - (
        PARTITION_TABLE_SECTORS + 1
    ) * SECTOR_SIZE
    target_backup_offset = backup_entries_lba * SECTOR_SIZE
    source_body_bytes = source_backup_offset - primary_bytes
    if source_body_bytes <= 0:
        raise AssertionError("canonical source body is unexpectedly empty")

    extent_list = [
        _generated_extent("primary-gpt", 0, primary_data),
        _source_extent(
            "canonical-body",
            primary_bytes,
            primary_bytes,
            source_body_bytes,
            image,
        ),
    ]
    retired_backup_bytes = min(source_bytes, target_backup_offset) - source_backup_offset
    if retired_backup_bytes > 0:
        extent_list.append(
            _generated_extent(
                "retired-source-backup-gpt",
                source_backup_offset,
                bytes(retired_backup_bytes),
            )
        )
    extent_list.append(
        _generated_extent(
            "target-backup-gpt",
            target_backup_offset,
            entries + backup_header,
        )
    )
    extents = tuple(extent_list)
    _validate_extents(extents, source_bytes=source_bytes, target_bytes=target_bytes)
    unwritten = _unwritten_ranges(extents, target_bytes)
    target_image_digest = _fully_defined_target_sha256(image, extents, unwritten)

    commitment_document: dict[str, object] = {
        "schema": TARGET_PLAN_SCHEMA,
        "source_sha256": str(metadata["sha256"]),
        "source_bytes": source_bytes,
        "target_bytes": target_bytes,
        "disk_guid": str(metadata["disk_guid"]),
        "partition_guid": str(metadata["partition_guid"]),
        "esp_sha256": str(metadata["esp_sha256"]),
        "esp_bytes": int(metadata["esp_bytes"]),
        "esp_first_lba": int(metadata["esp_first_lba"]),
        "esp_last_lba": esp_last_lba,
        "target_last_usable_lba": last_usable,
        "target_backup_entries_lba": backup_entries_lba,
        "target_backup_header_lba": backup_header_lba,
        "target_image_sha256": target_image_digest,
        "sector_size": SECTOR_SIZE,
        "extents": [extent.public() for extent in extents],
        "unwritten_policy": UNWRITTEN_POLICY,
        "unwritten_ranges": [
            {"offset": offset, "bytes": size} for offset, size in unwritten
        ],
    }
    plan_digest = _target_plan_commitment(commitment_document)
    return TargetMediaPlan(
        source_sha256=str(metadata["sha256"]),
        source_bytes=source_bytes,
        target_bytes=target_bytes,
        disk_guid=str(metadata["disk_guid"]),
        partition_guid=str(metadata["partition_guid"]),
        esp_sha256=str(metadata["esp_sha256"]),
        esp_bytes=int(metadata["esp_bytes"]),
        esp_first_lba=int(metadata["esp_first_lba"]),
        esp_last_lba=esp_last_lba,
        target_last_usable_lba=last_usable,
        target_backup_entries_lba=backup_entries_lba,
        target_backup_header_lba=backup_header_lba,
        extents=extents,
        unwritten_ranges=unwritten,
        target_plan_sha256=plan_digest,
        target_image_sha256=target_image_digest,
    )


def _require_safe_output(path: Path) -> None:
    """Reject an existing output unless it is an ordinary regular file.

    ``lstat`` is intentional: a symlink to a regular file is still an unsafe
    output identity.  The eventual rename replaces the directory entry and
    never opens the existing destination, so no device/FIFO target is followed.
    """

    try:
        mode = path.lstat().st_mode
    except FileNotFoundError:
        return
    except OSError as error:
        raise MediaError(f"cannot inspect output path {path}: {error}") from error
    if not stat.S_ISREG(mode):
        raise MediaError(f"output exists and is not a regular file: {path}")


def _write_atomic(path: Path, data: bytes) -> None:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
    except OSError as error:
        raise MediaError(f"cannot create output directory {path.parent}: {error}") from error
    _require_safe_output(path)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    temporary_created = False
    try:
        try:
            stream = temporary.open("xb")
            temporary_created = True
        except OSError as error:
            raise MediaError(f"cannot create temporary output {temporary}: {error}") from error
        with stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        _require_safe_output(path)
        try:
            os.replace(temporary, path)
        except OSError as error:
            raise MediaError(f"cannot replace output {path}: {error}") from error
    finally:
        if temporary_created:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass


def _emit(metadata: dict[str, object]) -> None:
    print(json.dumps(metadata, sort_keys=True, separators=(",", ":")))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    pack = commands.add_parser("pack", help="bind one ESP image into deterministic GPT media")
    pack.add_argument("--esp", type=Path, required=True)
    pack.add_argument("--output", type=Path, required=True)
    inspect = commands.add_parser("inspect", help="strictly validate OSTADIX GPT media")
    inspect.add_argument("image", type=Path)
    plan = commands.add_parser(
        "plan-target",
        help="derive a sparse GPT relocation plan for one exact target capacity",
    )
    plan.add_argument("image", type=Path)
    plan.add_argument("--target-bytes", type=int, required=True)
    args = parser.parse_args(argv)
    try:
        if args.command == "pack":
            image, metadata = build_image(_read_bounded(args.esp, MAX_ESP_BYTES))
            _write_atomic(args.output, image)
            _emit(metadata)
        elif args.command == "inspect":
            _emit(inspect_image(_read_bounded(args.image, MAX_IMAGE_BYTES)))
        else:
            _emit(
                plan_target_image(
                    _read_bounded(args.image, MAX_IMAGE_BYTES), args.target_bytes
                ).public()
            )
    except MediaError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
